//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace QuantLib {

public class SwaptionVolatilityStructure : VolatilityTermStructure {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal SwaptionVolatilityStructure(global::System.IntPtr cPtr, bool cMemoryOwn) : base(NQuantLibcPINVOKE.SwaptionVolatilityStructure_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SwaptionVolatilityStructure obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          NQuantLibcPINVOKE.delete_SwaptionVolatilityStructure(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public double volatility(Date start, Period length, double strike, bool extrapolate) {
    double ret = NQuantLibcPINVOKE.SwaptionVolatilityStructure_volatility__SWIG_0(swigCPtr, Date.getCPtr(start), Period.getCPtr(length), strike, extrapolate);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double volatility(Date start, Period length, double strike) {
    double ret = NQuantLibcPINVOKE.SwaptionVolatilityStructure_volatility__SWIG_1(swigCPtr, Date.getCPtr(start), Period.getCPtr(length), strike);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double volatility(double start, double length, double strike, bool extrapolate) {
    double ret = NQuantLibcPINVOKE.SwaptionVolatilityStructure_volatility__SWIG_2(swigCPtr, start, length, strike, extrapolate);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double volatility(double start, double length, double strike) {
    double ret = NQuantLibcPINVOKE.SwaptionVolatilityStructure_volatility__SWIG_3(swigCPtr, start, length, strike);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double blackVariance(Date start, Period length, double strike, bool extrapolate) {
    double ret = NQuantLibcPINVOKE.SwaptionVolatilityStructure_blackVariance__SWIG_0(swigCPtr, Date.getCPtr(start), Period.getCPtr(length), strike, extrapolate);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double blackVariance(Date start, Period length, double strike) {
    double ret = NQuantLibcPINVOKE.SwaptionVolatilityStructure_blackVariance__SWIG_1(swigCPtr, Date.getCPtr(start), Period.getCPtr(length), strike);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double blackVariance(double start, double length, double strike, bool extrapolate) {
    double ret = NQuantLibcPINVOKE.SwaptionVolatilityStructure_blackVariance__SWIG_2(swigCPtr, start, length, strike, extrapolate);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double blackVariance(double start, double length, double strike) {
    double ret = NQuantLibcPINVOKE.SwaptionVolatilityStructure_blackVariance__SWIG_3(swigCPtr, start, length, strike);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Date optionDateFromTenor(Period p) {
    Date ret = new Date(NQuantLibcPINVOKE.SwaptionVolatilityStructure_optionDateFromTenor(swigCPtr, Period.getCPtr(p)), true);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
