/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class AnalyticPTDHestonEngine extends PricingEngine {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected AnalyticPTDHestonEngine(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.AnalyticPTDHestonEngine_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AnalyticPTDHestonEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_AnalyticPTDHestonEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AnalyticPTDHestonEngine(PiecewiseTimeDependentHestonModel model, double relTolerance, long maxEvaluations) {
    this(QuantLibJNI.new_AnalyticPTDHestonEngine__SWIG_0(PiecewiseTimeDependentHestonModel.getCPtr(model), model, relTolerance, maxEvaluations), true);
  }

  public AnalyticPTDHestonEngine(PiecewiseTimeDependentHestonModel model, long integrationOrder) {
    this(QuantLibJNI.new_AnalyticPTDHestonEngine__SWIG_1(PiecewiseTimeDependentHestonModel.getCPtr(model), model, integrationOrder), true);
  }

  public AnalyticPTDHestonEngine(PiecewiseTimeDependentHestonModel model) {
    this(QuantLibJNI.new_AnalyticPTDHestonEngine__SWIG_2(PiecewiseTimeDependentHestonModel.getCPtr(model), model), true);
  }

}
