/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class BlackCapFloorEngine extends PricingEngine {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected BlackCapFloorEngine(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.BlackCapFloorEngine_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BlackCapFloorEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_BlackCapFloorEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BlackCapFloorEngine(YieldTermStructureHandle termStructure, QuoteHandle vol) {
    this(QuantLibJNI.new_BlackCapFloorEngine__SWIG_0(YieldTermStructureHandle.getCPtr(termStructure), termStructure, QuoteHandle.getCPtr(vol), vol), true);
  }

  public BlackCapFloorEngine(YieldTermStructureHandle termStructure, OptionletVolatilityStructureHandle vol) {
    this(QuantLibJNI.new_BlackCapFloorEngine__SWIG_1(YieldTermStructureHandle.getCPtr(termStructure), termStructure, OptionletVolatilityStructureHandle.getCPtr(vol), vol), true);
  }

}
