/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class YoYInflationCapFloor extends Instrument {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected YoYInflationCapFloor(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.YoYInflationCapFloor_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YoYInflationCapFloor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_YoYInflationCapFloor(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public double impliedVolatility(double price, YoYInflationTermStructureHandle curve, double guess, double accuracy, long maxEvaluations, double minVol, double maxVol) {
    return QuantLibJNI.YoYInflationCapFloor_impliedVolatility__SWIG_0(swigCPtr, this, price, YoYInflationTermStructureHandle.getCPtr(curve), curve, guess, accuracy, maxEvaluations, minVol, maxVol);
  }

  public double impliedVolatility(double price, YoYInflationTermStructureHandle curve, double guess, double accuracy, long maxEvaluations, double minVol) {
    return QuantLibJNI.YoYInflationCapFloor_impliedVolatility__SWIG_1(swigCPtr, this, price, YoYInflationTermStructureHandle.getCPtr(curve), curve, guess, accuracy, maxEvaluations, minVol);
  }

  public double impliedVolatility(double price, YoYInflationTermStructureHandle curve, double guess, double accuracy, long maxEvaluations) {
    return QuantLibJNI.YoYInflationCapFloor_impliedVolatility__SWIG_2(swigCPtr, this, price, YoYInflationTermStructureHandle.getCPtr(curve), curve, guess, accuracy, maxEvaluations);
  }

  public double impliedVolatility(double price, YoYInflationTermStructureHandle curve, double guess, double accuracy) {
    return QuantLibJNI.YoYInflationCapFloor_impliedVolatility__SWIG_3(swigCPtr, this, price, YoYInflationTermStructureHandle.getCPtr(curve), curve, guess, accuracy);
  }

  public double impliedVolatility(double price, YoYInflationTermStructureHandle curve, double guess) {
    return QuantLibJNI.YoYInflationCapFloor_impliedVolatility__SWIG_4(swigCPtr, this, price, YoYInflationTermStructureHandle.getCPtr(curve), curve, guess);
  }

}
